CREATE TABLE  "SV_IVAS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(45) NOT NULL ENABLE, 
	"PORCENTAJE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SV_IVAS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "SV_IVAS_DESC_UK" UNIQUE ("DESCRIPCION")
  USING INDEX  ENABLE
   )
/