CREATE TABLE  "SV_VENTAS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ESTADO_ID" NUMBER NOT NULL ENABLE, 
	"MONTO_TOTAL" NUMBER NOT NULL ENABLE, 
	"MONTO_SIN_IVA" NUMBER NOT NULL ENABLE, 
	"MONTO_IVA" NUMBER NOT NULL ENABLE, 
	"MOTIVO_ANULADO" VARCHAR2(2000), 
	"USER_WEB" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "SV_VENTAS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "SV_VENTAS" ADD CONSTRAINT "SV_VENTAS_ESTADO_FK" FOREIGN KEY ("ESTADO_ID")
	  REFERENCES  "SV_ESTADOS" ("ID") ENABLE
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_SV_VENTAS" 
  before insert on "SV_VENTAS"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "SV_VENTAS_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_SV_VENTAS" ENABLE
/